import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./AuthProvider.js";
import Authwrapper from "./Authwrapper";
import { Toaster } from "react-hot-toast";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable}  antialiased`}>
        <Toaster position="top-center"/>
        <AuthProvider>
          <Authwrapper>{children}</Authwrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
